apiVersion: v1
kind: Pod
metadata:
  name: krassercontainer # lobby
  labels:
    mcname: lobby
spec:
  volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
  containers:
    - name: krasserserver
      image: marctv/minecraft-papermc-server:latest
      ports:
        - name: mc-default-port
          containerPort: 25565
          protocol: TCP
      volumeMounts:
        - mountPath: "/data"
          name: minecraft-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mclobby
spec:
  selector:
    mcname: lobby
  ports:
    - name: minecraft
      targetPort: 25565
      port: 25565
      protocol: TCP
---



apiVersion: v1
kind: Pod
metadata:
  name: krassercontainer-2 # tannenwald
  labels:
    mcname: tannenwald
spec:
  volumes:
      - name: minecraft-data-2
        persistentVolumeClaim:
          claimName: minecraft-data-2
  containers:
    - name: krasserserver
      image: marctv/minecraft-papermc-server:latest
      ports:
        - name: mc-default-port
          containerPort: 25565
          protocol: TCP
      volumeMounts:
        - mountPath: "/data"
          name: minecraft-data-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mctannenbaum
spec:
  selector:
    mcname: tannenwald
  ports:
    - name: minecraft
      targetPort: 25565
      port: 25565
      protocol: TCP