apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  labels:
    app: velocity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: ghcr.io/krassegorganisation/blubb:latest
        ports:
        - containerPort: 25577
        volumeMounts:
          - name: mnt
            mountPath: /mnt
      initContainers:
      - name: init-secret-file
        image: busybox:1.28
        command: ['sh', '-c', "ls -la /mnt; echo test >> /mnt/test-file"]
        volumeMounts:
          - name: mnt
            mountPath: /mnt
      volumes:
      - name: mnt
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: velocity
spec:
  selector:
    app: velocity
  ports:
    - name: velocity
      targetPort: 25577
      port: 25577
      protocol: TCP