apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: ghcr.io/krassegorganisation/blubb:latest
        ports:
        - containerPort: 25577
        volumeMounts:
          - name: mnt
            mountPath: /mnt
        tty: true
        stdin: true
      initContainers:
      - name: init-secret-file
        image: busybox:1.28
        command: 
          - 'sh'
          - '-c'
          - |
            mkdir /mnt/secrets
            cp /mnt/secret-store/forwarding-secret /mnt/secrets/forwarding.secret
            cp /mnt/secret-store/private-key /mnt/secrets/private.key
            echo files in /mnt; ls -la /mnt
            echo files in /mnt/secrets; ls -la /mnt/secrets
        volumeMounts:
        - name: mnt
          mountPath: /mnt
        - name: secret-volume
          mountPath: /mnt/secret-store
      volumes:
      - name: mnt
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: velocity-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: velocity
spec:
  selector:
    app: velocity
  ports:
  - name: velocity
    targetPort: 25577
    port: 25577
    protocol: TCP