apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  labels:
    app: velocity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: ghcr.io/krassegorganisation/blubb:latest
        ports:
        - containerPort: 25577
---
apiVersion: v1
kind: Service
metadata:
  name: velocity
spec:
  selector:
    app: velocity
  ports:
    - name: velocity
      targetPort: 25577
      port: 25577
      protocol: TCP