apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: ghcr.io/krassegorganisation/blubb:latest
        ports:
        - containerPort: 25577
        volumeMounts:
          - name: mnt
            mountPath: /mnt
      initContainers:
      - name: init-secret-file
        image: busybox:1.28
        env:
          - name: FORWARDING_SECRET
            valueFrom:
              secretKeyRef:
                name: velocity-secrets
                key: forwarding-secret
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: velocity-secrets
                key: private-key
        command: [
          'sh', '-c',
          "echo files in /mnt; ls -la /mnt",
          "echo $FORWARDING_SECRET >> /mnt/secrets/forwarding.secret",
          "echo $PRIVATE_KEY >> /mnt/secrets/private.key"
        ]
        volumeMounts:
          - name: mnt
            mountPath: /mnt
      volumes:
      - name: mnt
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: velocity
spec:
  selector:
    app: velocity
  ports:
    - name: velocity
      targetPort: 25577
      port: 25577
      protocol: TCP