FROM ich777/fivemserver

RUN sed -i 's/30120/30124/g' configs/server.cfg
RUN sed -i 's/\#sv_master1/sv_master1/g' configs/server.cfg
RUN sed -i 's/sv_maxclients 32/sv_maxclients 10/g' configs/server.cfg
